services:
  db:
    image: postgres:14.1-alpine
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "generate_admin"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: generate-tech-app
    build:
      context: ./
    image: generate-tech-app
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      RUST_LOG: trace
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/postgres
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local
