services:
  db:
    image: postgres:14.1-alpine
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "generate_admin"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=money123
      - POSTGRES_DB=applications
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: generate-tech-app
    build:
      context: ./
    image: generate-tech-app
    depends_on:
      - db
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local
