# https://taskfile.dev

version: '3'

tasks:
  restart:
    cmds:
      - docker compose down --volumes
      - docker compose up
  db:
    - docker compose up db -d
  refresh-db:
    cmds:
      - docker compose down db --volumes
      - task: db

  connect:
    - psql postgres://postgres:postgres@localhost:5432/postgres

