# https://taskfile.dev

version: '3'

tasks:
  run:
    - RUST_LOG=info cargo run 
  up:
    - docker compose up -d
  down:
    - docker compose down
  restart:
    cmds:
      - docker compose down --volumes
      - docker compose up
  db:
    - docker compose up db -d
  refresh-db:
    cmds:
      - docker compose down db --volumes
      - task: db
  connect:
    - psql postgres://generate_admin:generate_tech_app@localhost:5432/applications

