# https://taskfile.dev

version: '3'

tasks:
  up:
    - docker compose --env-file .local.env up -d
  down:
    - docker compose down
  restart:
    cmds:
      - docker compose down --volumes
      - docker compose up
  db:
    - docker compose up db -d
  refresh-db:
    cmds:
      - docker compose down db --volumes
      - task: db
  connect:
    - psql postgres://postgres:postgres@localhost:5432/postgres

